version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: umabhai
      POSTGRES_PASSWORD: umabhai123
      POSTGRES_DB: umadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data: